### ISSUE TITLE
Titles of online articles

### ISSUE THREAD

**Issue by michal-h21** [wg030/biblatex-iso690_2021#1]
Thanks to our librarian mailing list, I've just found another bizarre rule in the new norm. According to section 7.4.2.3, online articles should have their title highlighted instead of the journal-title.  The old rule applies to articles that are only in print, so the journal title must be italicized in that case. This just gets more and more insane.

**Comment by wg030** [comment]
Yeah, some of the new rules are kind of weird and you wonder how much sense they really make.
When having a closer look at all examples you can even figure out that sometimes they do not stick to some of their own rules.
I would say that the norm has become quite messy and it seems obvious that there was no person or a group of persons who went through the whole final result checking the rules for consistency and reasonableness. 

Concerning this title rule you mentioned I already put it on my DOTO list and along with the examples that are concerned. I will likely add a package option like `emphtitle` that can be used on a per entry base indvidually. So something like
```
@article{maddox,
options = {emphtitle=true},
% [...]
}
```
is the solution I tend to propose for this issue right now. In fact I already started working on that lately.

**Comment by wg030** [comment]
I just realesed the beta version v0.3.
Exactly as planed I introduced the `emphtitle` (and also analogously the `emphbooktitle`, `emphmaintitle ` and `emphjournaltitle`) entry option, which can now be used as shown above. This allows us to highlight which ever title we want to on a per-entry basis.
Hence we can close this issue.

**Comment by wg030** [comment]
Successfully implemented since beta version v0.3.
